# Reusable workflow
# Generates the python packages for the CI pipeline (test) as well as the
# release pipeline.
name: Build Python Packages
on: [workflow_call]
jobs:
  conda:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        # Pip dependencies
        python -m pip install --upgrade pip
        pip install build
        pip install -r requirements.txt
        # Conda dependencies
        conda config --add channels conda-forge
        conda install --yes conda-build
        conda install --yes --file requirements.txt
    - name: Build Conda package
      run: |
        python setup.py bdist_conda
    - name: Copy Conda packages to local dist folder
      run: |
        mkdir -p dist
        cp -r /usr/share/miniconda/conda-bld/linux-64 ./dist
        cd dist
        conda convert -p osx-64 linux-64/*.tar.bz2
        conda convert -p win-64 linux-64/*.tar.bz2

    - name: Store the distribution packages
      uses: actions/upload-artifact@v3
      with:
        name: conda-dist
        path: |
          dist/*

  pypi:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        # Pip dependencies
        python -m pip install --upgrade pip
        pip install build
        pip install -r requirements.txt
    - name: Build Pip package
      run: |
        python setup.py sdist
    - name: Store the distribution packages
      uses: actions/upload-artifact@v3
      with:
        name: pypi-dist
        path: |
          dist/*
